Add IsInsideAreaByCodeEnum function
GeoWerkstatt/interlis-functions-ngk-so pull request #2
Opened 2024-01-24 14:15 UTC by domi-b

Resolves #1

2024-01-29 09:20 UTC, patrickackermann requested changes

2024-01-29 09:20 UTC, patrickackermann commented on src/test/data/IsInsideAreaByCodeEnum/TestData_Ok.xtf
> +                <TestSuite:code>code_3</TestSuite:code>
REQ: Überprüfen, dass es funktioniert, wenn es in den verwendeten Enum values eine Lücke hat. z.B. hier _code_4_ nehmen.

2024-01-30 07:20 UTC, domi-b commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/ngk/IsInsideAreaByCodeEnumIoxPlugin.java
> +        List<String> objectIds = objects.stream().map(IomObject::getobjectoid).collect(Collectors.toList());
Die Objekte sollten eigentlich immer in der gleichen Reihenfolge sein, daher ist es meiner Meinung nach nicht unbedingt nötig, die Ids noch alphabetisch zu sortieren.

2024-01-30 07:26 UTC, domi-b commented on src/main/java/ch/geowerkstatt/ilivalidator/extensions/functions/ngk/IsInsideAreaByCodeEnumIoxPlugin.java
> +                throw new IllegalStateException("unknown class in " + usageScope);
Der usageScope ist der Name des Constraints. Wenn getContextClass `null` zurückgibt, ist leider der Name der Klasse ebenfalls nicht bekannt, ansonsten sollte die Klasse in der Transferdescription gefunden werden.

2024-01-30 07:43 UTC, patrickackermann approved these changes

2024-01-30 08:04 UTC, merged