add 2.3 model, sample to signature
GeoWerkstatt/interlis-functions-ngk-so pull request #3
Opened 2024-02-20 15:59 UTC by olivergrimm

2024-02-20 16:09 UTC, domi-b commented on src/model/NGK_SO_FunctionsExt_23.ili
> +    !!@ fn.sample = "SET CONSTRAINT NGK_SO_FunctionsExt.IsInsideAreaByCodeEnum(THIS, "Geometrie" ,"Code");";
Q: Bei einem SET CONSTRAINT sollte es eher ALL sein anstelle von THIS?

2024-02-20 16:11 UTC, Philippluca requested changes

2024-02-20 16:11 UTC, Philippluca commented on src/model/NGK_SO_FunctionsExt_23.ili
> +END NGK_SO_FunctionsExt.
REQ: Whitespace am Ende von Files einfügen.

2024-02-20 16:11 UTC, Philippluca commented on src/model/NGK_SO_FunctionsExt_23.ili
> +  AT "mailto:info@geowerkstatt.ch" VERSION "2024-01-23" =
Q: Können wir hier in Zukunft einfach Änderungen am Modell vornehmen ohne diese mit SO zu besprechen? Ist die Mail / Version hier korrekt?

2024-02-27 09:11 UTC, olivergrimm commented on src/model/NGK_SO_FunctionsExt_23.ili
> +    !!@ fn.sample = "SET CONSTRAINT NGK_SO_FunctionsExt.IsInsideAreaByCodeEnum(THIS, "Geometrie" ,"Code");";
klar. ist korrigiert

2024-02-27 09:12 UTC, olivergrimm commented on src/model/NGK_SO_FunctionsExt_23.ili
> +END NGK_SO_FunctionsExt.
done

2024-02-27 09:14 UTC, olivergrimm commented on src/model/NGK_SO_FunctionsExt_23.ili
> +  AT "mailto:info@geowerkstatt.ch" VERSION "2024-01-23" =
guter Input. `mailto: `ist angepasst, die Version ist aktualisiert.

2024-02-27 15:22 UTC, Philippluca approved these changes

2024-02-27 15:28 UTC, merged